#!/bin/bash

##    Alejandro Suarez Cebrian (Responsable de la Oficina de Software Libre de la Universidad de Zaragoza)
##    Copyright (C) 2015  Alejandro Suarez Cebrian
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

export INSTALL_DIR=$HOME/osm
cd $INSTALL_DIR

export lastversion=$(wget http://josm.openstreetmap.de/ --quiet -O -|html2text |grep 'Download josm-tested.jar (version'| sed 's/)//g' |awk '{print $5}')
echo Ultima version online: $lastversion

max=0
for n in $(ls josm-*jar|sed 's/josm-//g' |sed 's/\.jar//');
   do ((n > max)) && max=$n
done;
echo Ultima version descargada: $max

#wmname LG3D
if (($max < $lastversion)); then 
   echo Descargando ultima version
   wget http://josm.openstreetmap.de/josm-tested.jar -O josm-${lastversion}.jar
   java $@ -jar josm-${lastversion}.jar
else
   java $@ -jar josm-${max}.jar
fi
